package cn.imust.domain.feedback;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class MessageExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public MessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSendPerIsNull() {
            addCriterion("send_per is null");
            return (Criteria) this;
        }

        public Criteria andSendPerIsNotNull() {
            addCriterion("send_per is not null");
            return (Criteria) this;
        }

        public Criteria andSendPerEqualTo(String value) {
            addCriterion("send_per =", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerNotEqualTo(String value) {
            addCriterion("send_per <>", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerGreaterThan(String value) {
            addCriterion("send_per >", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerGreaterThanOrEqualTo(String value) {
            addCriterion("send_per >=", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerLessThan(String value) {
            addCriterion("send_per <", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerLessThanOrEqualTo(String value) {
            addCriterion("send_per <=", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerLike(String value) {
            addCriterion("send_per like", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerNotLike(String value) {
            addCriterion("send_per not like", value, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerIn(List<String> values) {
            addCriterion("send_per in", values, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerNotIn(List<String> values) {
            addCriterion("send_per not in", values, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerBetween(String value1, String value2) {
            addCriterion("send_per between", value1, value2, "sendPer");
            return (Criteria) this;
        }

        public Criteria andSendPerNotBetween(String value1, String value2) {
            addCriterion("send_per not between", value1, value2, "sendPer");
            return (Criteria) this;
        }

        public Criteria andReceivePerIsNull() {
            addCriterion("receive_per is null");
            return (Criteria) this;
        }

        public Criteria andReceivePerIsNotNull() {
            addCriterion("receive_per is not null");
            return (Criteria) this;
        }

        public Criteria andReceivePerEqualTo(String value) {
            addCriterion("receive_per =", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerNotEqualTo(String value) {
            addCriterion("receive_per <>", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerGreaterThan(String value) {
            addCriterion("receive_per >", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerGreaterThanOrEqualTo(String value) {
            addCriterion("receive_per >=", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerLessThan(String value) {
            addCriterion("receive_per <", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerLessThanOrEqualTo(String value) {
            addCriterion("receive_per <=", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerLike(String value) {
            addCriterion("receive_per like", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerNotLike(String value) {
            addCriterion("receive_per not like", value, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerIn(List<String> values) {
            addCriterion("receive_per in", values, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerNotIn(List<String> values) {
            addCriterion("receive_per not in", values, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerBetween(String value1, String value2) {
            addCriterion("receive_per between", value1, value2, "receivePer");
            return (Criteria) this;
        }

        public Criteria andReceivePerNotBetween(String value1, String value2) {
            addCriterion("receive_per not between", value1, value2, "receivePer");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andSendMailIsNull() {
            addCriterion("send_mail is null");
            return (Criteria) this;
        }

        public Criteria andSendMailIsNotNull() {
            addCriterion("send_mail is not null");
            return (Criteria) this;
        }

        public Criteria andSendMailEqualTo(String value) {
            addCriterion("send_mail =", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotEqualTo(String value) {
            addCriterion("send_mail <>", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailGreaterThan(String value) {
            addCriterion("send_mail >", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailGreaterThanOrEqualTo(String value) {
            addCriterion("send_mail >=", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailLessThan(String value) {
            addCriterion("send_mail <", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailLessThanOrEqualTo(String value) {
            addCriterion("send_mail <=", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailLike(String value) {
            addCriterion("send_mail like", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotLike(String value) {
            addCriterion("send_mail not like", value, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailIn(List<String> values) {
            addCriterion("send_mail in", values, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotIn(List<String> values) {
            addCriterion("send_mail not in", values, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailBetween(String value1, String value2) {
            addCriterion("send_mail between", value1, value2, "sendMail");
            return (Criteria) this;
        }

        public Criteria andSendMailNotBetween(String value1, String value2) {
            addCriterion("send_mail not between", value1, value2, "sendMail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}